
name: Python application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    name: Build Python API
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0
    - name: Set up Python 3.12
      uses: actions/setup-python@v5.2.0
      with:
        python-version: "3.12"
    - name: build flask app
      working-directory: ./apps/python-api
      run: |
        docker build -t python-api:latest .
    # - name : Docker trigger
    #   uses: mitch1009/docker-trigger@main
    #   with:
    #     git_token: ${{ secrets.GITHUB_TOKEN }}
    #     release_name: python-api
    #     release_version: latest
    #     docker_image_vendor: docker.io
    #     docker_context_path: ./apps/python-api
  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    
  
