
name: Python application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:     
  build:
    runs-on: ubuntu-latest
    name: Build Python API
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0
    - name: Set up Python 3.12
      uses: actions/setup-python@v5.2.0
      with:
        python-version: "3.12"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: build flask app
      working-directory: ./apps/python-api
      run: |
        docker build -t ghcr.io/mitch1009/backend/python-api:latest .
   
  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: setup ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build flask app
      working-directory: ./apps/python-api
      run: |
        docker build -t ghcr.io/mitch1009/backend/python-api:latest .
    - name: push docker image
      run: |
        docker push ghcr.io/mitch1009/backend/python-api:latest
    
  
